[package]
name = "bevy-logic-circuit"
version = "0.0.1"
edition = "2021"
license = "Proprietary"
authors = ["Olivier Schyns"]

[dependencies]
# bevy framework
bevy  = {version="0.7.0", features=["dynamic"]}
serde = {version="1.0"  , features=["derive" ]}
bincode = "1.2.1"
